server:
  port: 8001

database:
  dbhost: 127.0.0.1
  dbport: 5433
  dbname: "mealo_users"
  dbuser: "postgresuser"
  dbpassword: "postgresPW"

#docker run -it -v pgdata:/var/lib/pgdata/data -p 5433:5432 --name postgres -e POSTGRES_USER=postgresuser -e POSTGRES_PASSWORD=postgresPW -e POSTGRES_DB=mealo_users -d postgres
  