-- Database: mealo_users

-- DROP DATABASE IF EXISTS mealo_users;
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
	ID INT GENERATED ALWAYS AS IDENTITY,
	User_ID TEXT NOT NULL UNIQUE,
	Name TEXT NOT NULL,
	Email TEXT NOT NULL,
	Picture TEXT NOT NULL,
	Created_At DATE,
  	Updated_At DATE,
  	Deleted_At DATE,
	PRIMARY KEY(ID)
);
DROP TABLE IF EXISTS recipes;
CREATE TABLE IF NOT EXISTS recipes (
	ID INT GENERATED ALWAYS AS IDENTITY,
	Recipe_ID TEXT NOT NULL,
	Is_Favorite BOOL NOT NULL DEFAULT FALSE,
	User_ID TEXT,
	Created_At DATE,
  	Updated_At DATE,
  	Deleted_At DATE,
	PRIMARY KEY(ID),
	CONSTRAINT fk_users
		FOREIGN KEY(User_ID)
			REFERENCES users(User_ID)
			ON DELETE CASCADE
);